#!/bin/bash
# Merge video files
# Part of the GIULIO ANDREOTTI suite


usage()
{
cat << EOF
usage: $0 files

Merge video files

EOF
}

FILE=

# Make sure we get file name as command line argument
# Else read it from standard input device
if [ "$1" == "" ]; then
   #FILE="/dev/stdin"
   usage
else
   FILE="$1"
   # make sure file exist and readable
   if [ ! -f $FILE ]; then
        echo "$FILE : does not exists"
        exit 1
   elif [ ! -r $FILE ]; then
        echo "$FILE: can not be read"
        exit 2
   fi
fi



#for i in "$FILE"
#do
	#echo "-----------------------------------------------------------------"
	#echo "Creating transport file for $i"
	#echo "-----------------------------------------------------------------"
	#echo ffmpeg -i "$i" -c copy -bsf:v h264_mp4toannexb -f mpegts "$i".ts
	#exit 1
	#ffmpeg -i "$i" -c copy -bsf:v h264_mp4toannexb -f mpegts "$i".ts
#done
	#echo "Transport file done now building ts files list:"
	#printf "file '%s'\n" ./*.mp4 > tempmytransportlist.txt

	#ffmpeg -f concat -safe 0 -i tempmytransportlist.txt -c copy -bsf:a aac_adtstoasc filefinal.mp4
	#ffmpeg -f concat -safe 0 -i tempmytransportlist.txt -c copy filefinal.mp4
	#melt *TRIM.mp4 -consumer avformat:filefinal.mp4 vcodec=libx264 vb=5M acodec=aac ab=128k
	melt "$FILE" -consumer avformat:filefinal.mp4 vcodec=libx264 vb=5M acodec=aac ab=128k
	
	#rm tempmytransportlist.txt
	#rm *.ts
